# Generated by Django 5.1.9 on 2025-05-24 06:32

import django.db.models.deletion
import exten_bot.bot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_completion_tokens', models.PositiveIntegerField(default=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='exten.bot', max_length=255)),
                ('privacy', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my function', max_length=255)),
                ('description', models.JSONField(default=exten_bot.bot.models.function_default)),
                ('privacy', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=exten_bot.bot.models.generate_uuid, max_length=32)),
                ('password', models.CharField(default=exten_bot.bot.models.generate_uuid, max_length=255)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(max_length=500)),
                ('instruction', models.TextField()),
                ('welcome_msg', models.TextField(blank=True, null=True)),
                ('transfer_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('max_tokens', models.PositiveIntegerField(default=4096)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bot.domain')),
                ('functions', models.ManyToManyField(blank=True, related_name='bots', to='bot.function')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bot.model')),
                ('voice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bot.voice')),
            ],
        ),
    ]
