# Generated by Django 5.1.9 on 2025-08-24 07:18

import django.db.models.deletion
import exten_bot.bot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('workflow', '0003_mcp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='functions',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='dify',
        ),
        migrations.AddField(
            model_name='bot',
            name='mcp',
            field=models.ForeignKey(blank=True, help_text='Mcp integration (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='workflow.mcp'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='domain',
            field=models.ForeignKey(help_text='SIP Server associated with the bot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bot.domain'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='Expiration date for the bot', null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='instruction',
            field=models.TextField(help_text='Instructions for the bot'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_tokens',
            field=models.PositiveIntegerField(default=4096, help_text='Maximum number of tokens'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='model',
            field=models.ForeignKey(help_text='Model used by the bot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bot.model'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the bot', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bot',
            name='password',
            field=models.CharField(default=exten_bot.bot.models.generate_uuid, help_text="Bot's password", max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Sampling temperature (0.0-1.0)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(help_text='OpenAI token', max_length=500),
        ),
        migrations.AlterField(
            model_name='bot',
            name='transfer_uri',
            field=models.CharField(blank=True, help_text='URI to transfer the conversation (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.CharField(default=exten_bot.bot.models.generate_uuid, help_text="Bot's username", max_length=32),
        ),
        migrations.AlterField(
            model_name='bot',
            name='voice',
            field=models.ForeignKey(help_text='Voice configuration for the bot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bot.voice'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='welcome_msg',
            field=models.TextField(blank=True, help_text='The message that the bot will say upon connecting.', null=True),
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
