# Generated by Django 5.1.9 on 2025-09-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_sample',
            field=models.FileField(blank=True, help_text='Example voice sample', null=True, upload_to='voice_samples/'),
        ),
    ]
