# Generated by Django 5.1.9 on 2025-08-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_mcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='domain',
            field=models.CharField(blank=True, default='exten.bot', help_text='SIP Server associated with the bot', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='type',
            field=models.CharField(choices=[('registrant', 'registrant'), ('registrar', 'registrar')], default='registrar', help_text='Type of bot', max_length=50),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
