# Generated by Django 5.1.9 on 2025-09-02 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my function', help_text='Name of the function', max_length=255)),
                ('url', models.URLField(help_text='URL of the function')),
                ('token', models.CharField(blank=True, help_text='Bearer Token of the url', max_length=1000, null=True)),
                ('json_schema', models.JSONField(help_text='JSON schema of the function')),
                ('input_schema', models.JSONField(blank=True, help_text='Input schema of the function', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField(default='http://localhost:8000', help_text='Base URL for the Mcp server')),
                ('api_key', models.CharField(blank=True, help_text='API key for accessing the Mcp server', max_length=255, null=True)),
                ('server_label', models.CharField(blank=True, help_text='Label of the server', max_length=255, unique=True)),
                ('require_approval', models.CharField(choices=[('never', 'Never'), ('always', 'Always')], default='never', max_length=255)),
                ('owner', models.ForeignKey(help_text='User who owns this Mcp configuration', on_delete=django.db.models.deletion.CASCADE, related_name='mcp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
