# Generated by Django 5.1.9 on 2025-05-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dify',
            name='expiration_date',
        ),
    ]
