# Generated by Django 5.1.9 on 2025-08-24 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_remove_dify_expiration_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dify',
            name='api_key',
            field=models.CharField(help_text='API key for accessing the Dify WorkFlow API', max_length=255),
        ),
        migrations.AlterField(
            model_name='dify',
            name='base_url',
            field=models.URLField(default='https://api.dify.ai/v1', help_text='Base URL for the Dify API'),
        ),
        migrations.AlterField(
            model_name='dify',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this Dify configuration', on_delete=django.db.models.deletion.CASCADE, related_name='dify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Mcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default='http://localhost:8000', help_text='Base URL for the Mcp server')),
                ('api_key', models.CharField(help_text='API key for accessing the Mcp server', max_length=255)),
                ('owner', models.ForeignKey(help_text='User who owns this Mcp configuration', on_delete=django.db.models.deletion.CASCADE, related_name='mcp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
