# Generated by Django 5.1.9 on 2025-08-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_mcp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dify',
        ),
    ]
