# Generated by Django 5.1.9 on 2025-08-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_mcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcp',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for accessing the Mcp server', max_length=255, null=True),
        ),
    ]
