# Generated by Django 5.1.9 on 2025-08-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='name',
            field=models.CharField(default='my function', help_text='Name of the function', max_length=255),
        ),
    ]
