# Generated by Django 5.1.9 on 2025-08-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='token',
            field=models.CharField(blank=True, help_text='Bearer Token of the url', max_length=1000, null=True),
        ),
    ]
