# Generated by Django 5.1.9 on 2025-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_function_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='input_schema',
            field=models.JSONField(blank=True, help_text='Input schema of the function', null=True),
        ),
    ]
